"""empty message

Revision ID: 6cb42d5a72bf
Revises: 
Create Date: 2021-06-02 15:44:46.856047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb42d5a72bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search'))
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('img1_name', sa.String(length=300), nullable=True),
    sa.Column('img1', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype1', sa.String(length=100), nullable=True),
    sa.Column('img2_name', sa.String(length=300), nullable=True),
    sa.Column('img2', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype2', sa.String(length=100), nullable=True),
    sa.Column('img3_name', sa.String(length=300), nullable=True),
    sa.Column('img3', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype3', sa.String(length=100), nullable=True),
    sa.Column('img4_name', sa.String(length=300), nullable=True),
    sa.Column('img4', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype4', sa.String(length=100), nullable=True),
    sa.Column('img5_name', sa.String(length=300), nullable=True),
    sa.Column('img5', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype5', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('nickname', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('stu_name', sa.String(length=300), nullable=False),
    sa.Column('stu', sa.LargeBinary(), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('nickname', name=op.f('uq_user_nickname')),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone', name=op.f('uq_user_phone'))
    )
    op.create_table('S__answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], name=op.f('fk_S__answer_search_id_search'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_S__answer'))
    )
    op.create_table('T__answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name=op.f('fk_T__answer_transfer_id_transfer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_T__answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T__answer')
    op.drop_table('S__answer')
    op.drop_table('user')
    op.drop_table('transfer')
    op.drop_table('search')
    # ### end Alembic commands ###
